/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Command gen-ui-policy writes the dashboard's copy of the API's enforcement
// table: ui/src/lib/policy.generated.ts, from internal/api/policy.go.
//
// The dashboard decides which controls to render, and it has to decide it from
// the same rules the API enforces. Writing those rules twice is how a UI ends
// up hiding something the API allows, or offering something it refuses — so
// the second copy is generated, the way this repository generates the CRDs
// from the API types and the chart's templates from the CRDs.
//
// It reads the table by importing internal/api and asking it (api.PolicyTable),
// rather than by parsing policy.go: the table is a Go value, and a parser over
// its source would be a second, worse implementation of the Go compiler that
// breaks the first time a row is written in a way it did not expect.
//
// Run it with `make ui-policy`. CI fails when the checked-in output differs
// from a fresh run.
package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"os"
	"strings"

	"github.com/Bermos/Kitchen/internal/api"
)

// defaultOut is where the dashboard keeps it, relative to the repository root
// — which is where `make ui-policy` runs this from.
const defaultOut = "ui/src/lib/policy.generated.ts"

func main() {
	out := flag.String("o", defaultOut, "where to write the generated TypeScript module")
	flag.Parse()

	if err := run(*out); err != nil {
		fmt.Fprintf(os.Stderr, "gen-ui-policy: %v\n", err)
		os.Exit(1)
	}
}

func run(out string) error {
	policy, err := api.PolicyTable()
	if err != nil {
		return err
	}
	module, err := render(policy)
	if err != nil {
		return err
	}
	if err := os.WriteFile(out, module, 0o644); err != nil {
		return fmt.Errorf("writing %s: %w", out, err)
	}
	fmt.Printf("gen-ui-policy: %s (%d routes)\n", out, len(policy.Routes))
	return nil
}

// render is the whole of the emitted module.
//
// Everything about it is deterministic: the routes keep the table's own order,
// which groups them the way policy.go groups them, and nothing is derived from
// a map. A generator whose output moves between runs makes the drift check
// fail at random, which teaches everybody to ignore it.
func render(policy api.Policy) ([]byte, error) {
	buf := &bytes.Buffer{}
	buf.WriteString(header)

	if err := writeRoles(buf, policy); err != nil {
		return nil, err
	}
	if err := writeKinds(buf); err != nil {
		return nil, err
	}
	if err := writeRoutes(buf, policy); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

const header = `/**
 * The API's enforcement table, as the dashboard's copy of it.
 *
 * Generated by hack/gen-ui-policy from internal/api/policy.go. DO NOT EDIT.
 * Run ` + "`make ui-policy`" + ` to refresh it; CI fails when the checked-in copy
 * and a fresh run differ.
 *
 * It is data and no logic, on purpose. The questions the dashboard actually
 * asks — may this person redeploy, and what do I say when they may not — are
 * answered by the hand-written helper next to it in ./policy, which is where
 * anything that has to be reasoned about belongs. What is here is only what
 * the API's own table says, so that the two cannot disagree.
 */

`

// writeRoles emits the two orderings. They are arrays rather than a set
// because the order is the whole point: "at least developer" is a comparison,
// and it is internal/access's comparison, not a second opinion about which
// role outranks which.
func writeRoles(buf *bytes.Buffer, policy api.Policy) error {
	platform, err := literalStrings(policy.PlatformRoles)
	if err != nil {
		return err
	}
	project, err := literalStrings(policy.ProjectRoles)
	if err != nil {
		return err
	}

	fmt.Fprintf(buf, `/** The platform roles, weakest first: exactly one per account. */
export const PLATFORM_ROLES = [%s] as const;
export type PlatformRole = (typeof PLATFORM_ROLES)[number];

/** The project roles, weakest first: one per account, per project. */
export const PROJECT_ROLES = [%s] as const;
export type ProjectRole = (typeof PROJECT_ROLES)[number];

`, platform, project)
	return nil
}

// writeKinds emits what a route may ask of its caller, and the shape one row
// takes. The prose on each kind is here rather than generated from Go: it is
// what a dashboard author needs to know about the kind, which is not the same
// thing the API's own comments say.
func writeKinds(buf *bytes.Buffer) error {
	kinds, err := literalStrings(everyKind())
	if err != nil {
		return err
	}

	fmt.Fprintf(buf, `/**
 * What a route asks of its caller.
 *
 * - %[2]q — any valid token. The caller's own identity is the whole of it.
 * - %[3]q — the platform's operators alone.
 * - %[4]q — at least `+"`role`"+` on the project the request is about.
 * - %[5]q — any valid token, and the answer is narrowed to the caller's own
 *   projects. Admission is never the question here; completeness is.
 * - %[6]q — any valid token, and the *body* varies by the caller's platform
 *   role. Which parts are missing is the handler's own business and is not
 *   something this table can say.
 */
export const REQUIREMENT_KINDS = [%[1]s] as const;
export type RequirementKind = (typeof REQUIREMENT_KINDS)[number];

/** One row's answer to "who may call this". */
export interface Requirement {
  kind: RequirementKind;
  /** The project role wanted, set only for %[4]q. */
  role?: ProjectRole;
  /**
   * The operation in the words a refusal uses — "redeploying", "changing the
   * platform's settings" — so a disabled control can be explained in the same
   * vocabulary the API's own 403 uses. Absent for the kinds that never refuse
   * a caller holding a valid token.
   */
  doing?: string;
}

`, kinds, api.PolicyAuthenticated, api.PolicyOperator, api.PolicyProjectRole,
		api.PolicyVisibleProjects, api.PolicyRoleShapedBody)
	return nil
}

// everyKind is the requirement kinds in the order the constants declare them,
// whether or not the table currently has a row of each: the union is the
// API's whole vocabulary, not a summary of today's table.
func everyKind() []string {
	return []string{
		api.PolicyAuthenticated,
		api.PolicyOperator,
		api.PolicyProjectRole,
		api.PolicyVisibleProjects,
		api.PolicyRoleShapedBody,
	}
}

// writeRoutes emits the table itself: a union of every pattern the API serves,
// and the requirement each carries.
//
// The union is what makes the dashboard's copy load-bearing rather than
// decorative. A route the table renames stops compiling everywhere the
// dashboard named it, which is the TypeScript half of the rule that a route
// added to policy.go without a requirement does not compile in Go.
func writeRoutes(buf *bytes.Buffer, policy api.Policy) error {
	if len(policy.Routes) == 0 {
		return errors.New("the enforcement table is empty")
	}

	buf.WriteString("/** Every pattern the API serves, spelled as the API's own table spells it. */\n")
	buf.WriteString("export type Route =\n")
	for _, route := range policy.Routes {
		pattern, err := literal(route.Pattern)
		if err != nil {
			return err
		}
		fmt.Fprintf(buf, "  | %s\n", pattern)
	}
	buf.WriteString(";\n\n")

	buf.WriteString(`/**
 * What every route requires. Keyed by the pattern, so a lookup is the same
 * string the API registers the route under.
 */
export const POLICY: Readonly<Record<Route, Requirement>> = {
`)
	for _, route := range policy.Routes {
		row, err := renderRoute(route)
		if err != nil {
			return err
		}
		buf.WriteString(row)
	}
	buf.WriteString("};\n")
	return nil
}

// renderRoute is one entry of the POLICY record, on one line. One line per
// route keeps the diff of a role change to the row that changed.
func renderRoute(route api.PolicyRoute) (string, error) {
	pattern, err := literal(route.Pattern)
	if err != nil {
		return "", err
	}
	kind, err := literal(route.Kind)
	if err != nil {
		return "", err
	}

	fields := []string{fmt.Sprintf("kind: %s", kind)}
	if route.Role != "" {
		role, err := literal(route.Role)
		if err != nil {
			return "", err
		}
		fields = append(fields, fmt.Sprintf("role: %s", role))
	}
	if route.Doing != "" {
		doing, err := literal(route.Doing)
		if err != nil {
			return "", err
		}
		fields = append(fields, fmt.Sprintf("doing: %s", doing))
	}
	return fmt.Sprintf("  %s: { %s },\n", pattern, strings.Join(fields, ", ")), nil
}

// literal is a Go string as a TypeScript one. It goes through the JSON encoder
// because JSON's string escaping is a subset of TypeScript's — Go's own
// strconv.Quote is not, since it escapes astral characters as \U0001F600,
// which JavaScript does not accept.
func literal(s string) (string, error) {
	encoded, err := json.Marshal(s)
	if err != nil {
		return "", fmt.Errorf("cannot write %q as a TypeScript string: %w", s, err)
	}
	return string(encoded), nil
}

// literalStrings is a list of them, comma-separated, for a one-line array.
func literalStrings(values []string) (string, error) {
	out := make([]string, 0, len(values))
	for _, value := range values {
		encoded, err := literal(value)
		if err != nil {
			return "", err
		}
		out = append(out, encoded)
	}
	return strings.Join(out, ", "), nil
}
