/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package controller

import (
	"context"
	"strings"
	"testing"
	"time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/utils/ptr"

	kitchenv1alpha1 "github.com/Bermos/Kitchen/api/v1alpha1"
	"github.com/Bermos/Kitchen/internal/attestation"
)

// A bill of materials for an image the platform did not build (#309).
//
// The one thing every test here is really about: a document the platform
// generated by unpacking somebody else's layers is not the same artefact as
// one the publisher stands behind, and the two must never be shown as one.

// vendoredArtifact is an attested vendored artifact carrying whatever
// evidence it is given.
func vendoredArtifact(evidence ...kitchenv1alpha1.ArtifactEvidence) *kitchenv1alpha1.ArtifactStatus {
	return &kitchenv1alpha1.ArtifactStatus{
		Repository: "ghcr.io/vendor/app",
		Digest:     "sha256:" + strings.Repeat("1", 64),
		SourceType: kitchenv1alpha1.ArtifactSourceVendored,
		AttestedAt: ptr.To(metav1.NewTime(time.Now())),
		Evidence:   evidence,
	}
}

func TestOnlyAVendoredArtifactWithNoBillOfMaterialsWantsOne(t *testing.T) {
	built := &kitchenv1alpha1.Build{Status: kitchenv1alpha1.BuildStatus{
		Artifact: &kitchenv1alpha1.ArtifactStatus{
			Repository: "registry.example.com/shop",
			Digest:     "sha256:" + strings.Repeat("a", 64),
			SourceType: kitchenv1alpha1.ArtifactSourceBuilt,
			AttestedAt: ptr.To(metav1.Now()),
		},
	}}
	if len(observableArtifacts(built)) != 0 {
		t.Error("a built artifact wants a generated bill of materials; the builder produced one")
	}

	// The vendor published one. Generating a second would be two answers to
	// one question, and a rescan would have to choose between them.
	published := &kitchenv1alpha1.Build{Status: kitchenv1alpha1.BuildStatus{
		Artifact: vendoredArtifact(kitchenv1alpha1.ArtifactEvidence{
			PredicateType: attestation.PredicateSPDX, Source: sourceVendorAsserted,
		}),
	}}
	if len(observableArtifacts(published)) != 0 {
		t.Error("the platform would generate a bill of materials beside the vendor's own")
	}

	// Nothing could be attached at all, so there is nowhere to put a
	// generated document either — running a scanner would spend an
	// application namespace on a file nothing can sign.
	unattested := &kitchenv1alpha1.Build{Status: kitchenv1alpha1.BuildStatus{
		Artifact: vendoredArtifact(),
	}}
	unattested.Status.Artifact.AttestedAt = nil
	if len(observableArtifacts(unattested)) != 0 {
		t.Error("a scanner would run for an artifact nothing can be attached to")
	}

	// A run that already failed is terminal, for the reason a gate's is: a
	// retry that eventually succeeded would leave a build whose evidence
	// says the generator works and whose history says it did not.
	failed := &kitchenv1alpha1.Build{Status: kitchenv1alpha1.BuildStatus{Artifact: vendoredArtifact()}}
	failed.Status.Artifact.ObservedSBOM = &kitchenv1alpha1.ObservedSBOMStatus{
		Phase: kitchenv1alpha1.GateFailed,
	}
	if len(observableArtifacts(failed)) != 0 {
		t.Error("a failed generation was retried")
	}

	wants := &kitchenv1alpha1.Build{Status: kitchenv1alpha1.BuildStatus{Artifact: vendoredArtifact()}}
	if len(observableArtifacts(wants)) != 1 {
		t.Error("a vendored artifact with no bill of materials was not offered one")
	}
}

func TestAGeneratedBillOfMaterialsIsAttestedAsThePlatformsOwnObservation(t *testing.T) {
	reconciler, attester, build, project := vendorFixtures(t)
	build.Status.Artifact = vendoredArtifact()
	attester.blobs = map[string][]byte{
		"sha256:beef": []byte(`{"spdxVersion":"SPDX-2.3","name":"vendor/app"}`),
	}

	status := &kitchenv1alpha1.ObservedSBOMStatus{}
	artifact := kitchenv1alpha1.BuildArtifact{Artifact: build.Status.Artifact}
	if err := reconciler.attestObservedSBOM(context.Background(), build, project,
		gateReport{Gate: observedSBOMName, Blob: "sha256:beef"}, artifact, status); err != nil {
		t.Fatal(err)
	}

	// The document carries SPDX's own predicate type — it has to, or the
	// rescan and require-sbom would not read it — and the index is what says
	// whose bill of materials it is.
	if status.PredicateType != attestation.PredicateSPDX {
		t.Errorf("attested under %q, want SPDX's own URI", status.PredicateType)
	}
	if len(build.Status.Artifact.Evidence) != 1 {
		t.Fatalf("the artifact indexes %d attestations, want the generated document",
			len(build.Status.Artifact.Evidence))
	}
	entry := build.Status.Artifact.Evidence[0]
	if entry.Source != sourcePlatformObserved {
		t.Errorf("the generated document is indexed %q, want %q — it is not the vendor's claim",
			entry.Source, sourcePlatformObserved)
	}

	// And the predicate is the document, verbatim: a bill of materials
	// rewritten by something that did not scan the image is a claim by the
	// rewriter.
	statement, err := attester.attached[0].Statement()
	if err != nil {
		t.Fatal(err)
	}
	if string(statement.Predicate) != `{"spdxVersion":"SPDX-2.3","name":"vendor/app"}` {
		t.Errorf("the predicate was re-encoded: %s", statement.Predicate)
	}
}

func TestTheGeneratorSaysWhichFormatItEmitted(t *testing.T) {
	spdx, err := billOfMaterialsType([]byte(`{"spdxVersion":"SPDX-2.3"}`))
	if err != nil || spdx != attestation.PredicateSPDX {
		t.Errorf("SPDX read as %q (%v)", spdx, err)
	}
	cyclone, err := billOfMaterialsType([]byte(`{"bomFormat":"CycloneDX","specVersion":"1.6"}`))
	if err != nil || cyclone != attestation.PredicateCycloneDX {
		t.Errorf("CycloneDX read as %q (%v)", cyclone, err)
	}
	// A predicate type is a promise about the bytes under it, so a document
	// that is neither is refused rather than attested as one of them.
	if _, err := billOfMaterialsType([]byte(`{"findings":[]}`)); err == nil {
		t.Error("a document that is neither format was attested as a bill of materials")
	}
}

func TestTheGeneratorPodIsPointedAtTheDigestAndGivenNothingElse(t *testing.T) {
	_, _, build, project := vendorFixtures(t)
	kitchen := &kitchenv1alpha1.Kitchen{}
	artifactRef := "ghcr.io/vendor/app@sha256:" + strings.Repeat("1", 64)

	job := observedSBOMJob("shop-bld-1-sbom", "kitchen-app-shop", build, project, kitchen,
		"", artifactRef, VendorSBOMGeneratorImage, "operator:dev")

	generator := job.Spec.Template.Spec.InitContainers[0]
	if generator.Args[0] != artifactRef {
		t.Errorf("the generator was pointed at %q, want the digest the platform deploys", generator.Args[0])
	}
	if generator.Image != VendorSBOMGeneratorImage {
		t.Errorf("the generator image is %q", generator.Image)
	}
	// It is an image somebody else wrote, running in an application's
	// namespace: no token, no cluster, an unprivileged user.
	if token := job.Spec.Template.Spec.AutomountServiceAccountToken; token == nil || *token {
		t.Error("the generator pod was given a service account token")
	}
	if user := generator.SecurityContext.RunAsUser; user == nil || *user != 1000 {
		t.Error("the generator does not run as an unprivileged user")
	}
	if limit := job.Spec.BackoffLimit; limit == nil || *limit != 0 {
		t.Error("a generation that did not run would be retried into looking like one that did")
	}
}
