/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package api

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"reflect"
	"sort"
	"strings"

	apierrors "k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"sigs.k8s.io/controller-runtime/pkg/client"

	kitchenv1alpha1 "github.com/Bermos/Kitchen/api/v1alpha1"
	"github.com/Bermos/Kitchen/internal/access"
)

// The enforcement table: every route this API serves, next to what it asks of
// its caller. It is the artefact, not a convenience — Handler registers *from*
// this list, so a route that is added without a requirement is a route that
// does not compile, and the dashboard's own copy of the rules is generated by
// reading it rather than written twice.
//
// The model it implements is docs/AUTH.md, "Who may do what", and it is
// implemented rather than restated: every membership question goes to
// internal/access, which the forward-auth gate asks as well. Nothing here
// decides who holds which role.
//
// Two things are worth knowing before reading the table:
//
//   - **The guard runs inside routing, not in front of it.** A requirement has
//     to resolve which project a request is about, and `req.PathValue` exists
//     only once the mux has matched a pattern. So each handler is wrapped as it
//     is registered; the token check (see authenticated) still sits outside the
//     whole mux, where it belongs.
//   - **A caller who may not see an object is told it does not exist.** Not
//     403: on a platform where developers are not meant to see each other's
//     projects, "you may not know whether billing exists" is the answer. A 403
//     is only for a caller who holds *some* role on the project and not enough
//     of one — which is exactly the refusal that can name the role it wanted.

// requirementKind is what a route asks of its caller.
//
// The last two are not weaker requirements; they are the two places where
// authorization is not a yes/no about the whole route, and they are in the
// table so that a reader can see the route does something beyond admitting or
// refusing (docs/AUTH.md: "A whole route is the unit of authorization.
// Filtering a response body by role is the exception").
type requirementKind uint8

const (
	// requireAuthenticated admits any valid token. It is what a route asks
	// when the caller's own identity is the whole of the authorization:
	// creating a project, and reading who you are.
	requireAuthenticated requirementKind = iota
	// requireOperator admits the platform's operators alone.
	requireOperator
	// requireProjectRole admits a caller holding at least requirement.Role on
	// the project the request is about, which requirement.Project resolves.
	requireProjectRole
	// requireVisibleProjects admits any valid token and narrows what the
	// handler answers to access.VisibleProjects — the cross-project reads,
	// where "everything" means everything of the caller's.
	requireVisibleProjects
	// requireRoleShapedBody admits any valid token and hands the handler the
	// caller's platform role — and the visible-project scope, since a body
	// shaped by role can still carry rows that name projects — because the
	// body varies by it. It is the class
	// docs/AUTH.md calls the exception to "a whole route is the unit of
	// authorization", and it stays an exception: a route belongs here only
	// when the same page is the answer for both people and a second endpoint
	// would double a surface for one payload. Two routes qualify. GET /status
	// is the dashboard's home page for a member and for an operator. GET
	// /connections is the connection picker: a project cannot exist without a
	// gitSource and a registry connection to name, so a member who cannot see
	// that a connection exists cannot fill in the first form on the platform
	// — and what they get back is names, capabilities and readiness, in a
	// shape of its own (connectionChoiceView), never the operator's view with
	// fields blanked out.
	requireRoleShapedBody
)

// requirement is one row's answer to "who may call this".
type requirement struct {
	// Kind is which authority the route wants.
	Kind requirementKind
	// Role is the project role Kind requireProjectRole wants, and is
	// ProjectRoleNone for every other kind.
	Role access.ProjectRole
	// Project resolves which Project the request is about. It is set for
	// requireProjectRole and empty otherwise.
	Project projectResolver
	// Doing names the operation in the words a refusal uses — "redeploying",
	// "changing the platform's settings" — so that every 403 reads like a
	// sentence without a per-handler string being written anywhere.
	Doing string
}

// route is one registered pattern: what it answers on, what answers it, and
// what it asks of the caller first.
type route struct {
	Pattern  string
	Handler  http.HandlerFunc
	Requires requirement
}

// The five requirement constructors. They exist so the table below is a list
// of facts rather than of struct literals with four fields each, and so that a
// requirement cannot be half-written: a project role always arrives with the
// resolver that finds its project.

// anyCaller is what a route asks when a valid token is the whole of it.
func anyCaller() requirement {
	return requirement{Kind: requireAuthenticated}
}

// operatorOnly is the platform's own surface. `doing` completes the sentence
// "<doing> needs the operator role".
func operatorOnly(doing string) requirement {
	return requirement{Kind: requireOperator, Doing: doing}
}

// onProject wants a role on the project `from` resolves. `doing` completes
// the sentence "<doing> needs developer".
func onProject(role access.ProjectRole, from projectResolver, doing string) requirement {
	return requirement{Kind: requireProjectRole, Role: role, Project: from, Doing: doing}
}

// acrossProjects is a read over every project, answered about the caller's
// own. The handler reads the scope with scopeFrom.
func acrossProjects() requirement {
	return requirement{Kind: requireVisibleProjects}
}

// byRole is a route whose body varies by the caller's platform role. The
// handler reads it with platformRoleFrom, and — for the parts of the body that
// are a list of somebody's projects rather than a fact about the platform —
// with scopeFrom.
//
// `doing` names the operation the same way operatorOnly's does. Nothing built
// from it is ever a refusal — this kind refuses nobody — but the table is read
// as well as executed: the dashboard's copy of the rules is generated from it,
// and a row that says only "any account" would leave a reader unable to tell a
// route that answers everybody the same thing from one that answers everybody
// something different.
func byRole(doing string) requirement {
	return requirement{Kind: requireRoleShapedBody, Doing: doing}
}

// routes is the table. Every pattern the API serves is here, with the role it
// requires; Handler registers from this and from nothing else.
//
// It is a method because the handlers are the server's. Everything else in a
// row is a constant, which is what keeps the table readable by the generator
// that gives the dashboard its copy.
func (s *Server) routes() []route {
	return []route{
		// Projects. Creating one is self-service — any account may, and
		// becomes its admin — and the list is filtered rather than refused.
		{"GET /api/v1/projects", s.listProjects, acrossProjects()},
		{"POST /api/v1/projects", s.createProject, anyCaller()},
		{"GET /api/v1/projects/{name}", s.getProject, onProject(access.ProjectViewer, ofProject, "reading a project")},
		{"PATCH /api/v1/projects/{name}", s.patchProject,
			onProject(access.ProjectAdmin, ofProject, "changing a project's settings")},
		// Environment variables are the one thing on a project that is the day
		// job rather than the project's own settings (docs/AUTH.md lists them
		// under developer, and the git source, the registry and the previews
		// policy under admin). They are a route of their own rather than a
		// field the admin route inspects, because a whole route is the unit of
		// authorization here: a handler that decided by which key the body
		// carried would be the exception the model keeps for response bodies,
		// applied to a write.
		{"PATCH /api/v1/projects/{name}/env", s.patchProjectEnv,
			onProject(access.ProjectDeveloper, ofProject, "changing a project's environment variables")},
		{"DELETE /api/v1/projects/{name}", s.deleteProject,
			onProject(access.ProjectAdmin, ofProject, "deleting a project")},
		{"GET /api/v1/projects/{name}/builds", s.listProjectBuilds,
			onProject(access.ProjectViewer, ofProject, "reading a project's builds")},
		{"POST /api/v1/projects/{name}/builds", s.createBuild,
			onProject(access.ProjectDeveloper, ofProject, "starting a build")},
		{"GET /api/v1/projects/{name}/releases", s.listProjectReleases,
			onProject(access.ProjectViewer, ofProject, "reading a project's releases")},
		{"GET /api/v1/projects/{name}/environments", s.listProjectEnvironments,
			onProject(access.ProjectViewer, ofProject, "reading a project's environments")},
		// The audit pack (#142): one project's whole compliance answer for
		// one window, as a document that leaves the platform.
		//
		// **Operator, and it is the subject matter rather than caution.** A
		// route's guard has to be the strictest thing in its body, and this
		// body folds three operator-only reads into a project's evidence:
		// the recertification cycles that looked at this project's grants —
		// whose signed artefacts cover every other project's too, carried
		// verbatim because a re-encoded envelope does not verify — the
		// platform's retention model, and the audit chain's anchor. A
		// project admin who could export it would read, in one file, what
		// three routes refuse them separately.
		//
		// It is also who takes one. An audit pack is produced by the
		// institution's second line for somebody outside it, not by the team
		// that deploys; and the application team is not left worse off,
		// because every project-scoped part of it — the inventory, the
		// promotions, the decisions, the exceptions, the drift, the project's
		// own audit records — is already a viewer's read of its own.
		{"GET /api/v1/projects/{name}/audit-pack", s.projectAuditPack,
			operatorOnly("exporting a project's audit pack")},

		// Membership. It is the project's own admin who adds and removes
		// people, which is the whole point: an operator holds admin on every
		// project (access.ProjectRoleFor) and so needs no case of their own
		// here, and everyone else stops needing to go and find one.
		//
		// Only the writes are admin's. Reading who is on a project is part of
		// knowing what the project is — a viewer opening its People tab would
		// otherwise be refused on load — and docs/AUTH.md puts membership
		// *writes* behind admin, not the list.
		{"GET /api/v1/projects/{name}/members", s.listMembers,
			onProject(access.ProjectViewer, ofProject, "reading a project's members")},
		{"POST /api/v1/projects/{name}/members", s.addMember,
			onProject(access.ProjectAdmin, ofProject, "adding somebody to a project")},
		{"PATCH /api/v1/projects/{name}/members", s.changeMemberRole,
			onProject(access.ProjectAdmin, ofProject, "changing somebody's role on a project")},
		{"DELETE /api/v1/projects/{name}/members", s.removeMember,
			onProject(access.ProjectAdmin, ofProject, "removing somebody from a project")},

		// CI keys. A key is a member of the project — a machine account with a
		// grant in the same `spec.access` (keys.go) — so issuing one is adding
		// a member, and adding a member is admin's. The list follows the
		// membership list for the same reason: it *is* the membership list,
		// with the non-human half of it shown, and it carries no key value —
		// only the prefix the issuer keeps, which is useless as a credential.
		{"GET /api/v1/projects/{name}/keys", s.listKeys,
			onProject(access.ProjectViewer, ofProject, "reading a project's CI keys")},
		{"POST /api/v1/projects/{name}/keys", s.createKey,
			onProject(access.ProjectAdmin, ofProject, "issuing a CI key for a project")},
		{"DELETE /api/v1/projects/{name}/keys/{key}", s.deleteKey,
			onProject(access.ProjectAdmin, ofProject, "revoking a project's CI key")},

		// Builds.
		{"GET /api/v1/builds", s.listBuilds, acrossProjects()},
		{"GET /api/v1/builds/{name}", s.getBuild, onProject(access.ProjectViewer, ofBuild, "reading a build")},
		{"POST /api/v1/builds/{name}/cancel", s.cancelBuild,
			onProject(access.ProjectDeveloper, ofBuild, "cancelling a build")},
		{"GET /api/v1/builds/{name}/logs", s.buildLogs,
			onProject(access.ProjectViewer, ofBuild, "reading a build's logs")},
		{"GET /api/v1/builds/{name}/attestations", s.buildAttestations,
			onProject(access.ProjectViewer, ofBuild, "reading a build's attestations")},
		// Submitting a gate result is asserting something about the project's
		// artifact, which is a developer's write rather than a viewer's read —
		// and a CI key, which is what usually submits one, is a developer on
		// exactly one project.
		{"POST /api/v1/builds/{name}/gates", s.submitGate,
			onProject(access.ProjectDeveloper, ofBuild, "submitting a quality gate result")},
		// Exploitability assertions. Reading them is a viewer's read like any
		// other evidence — and it is the read that makes a suppression
		// visible, so it is deliberately no harder to get at than the
		// findings themselves.
		//
		// Submitting one is **admin's**, and that is the one place this
		// endpoint parts company with the gate it otherwise resembles. A gate
		// result is a fact about an artifact; a not_affected statement is an
		// assertion whose effect is to make a finding stop counting, which is
		// nearer to approving a break-glass exception than to reporting a
		// scan. A CI key is a developer on exactly one project and therefore
		// cannot file one, which is intended: an artifact's own pipeline
		// asserting that its own findings do not apply is precisely the
		// self-marked homework the suite is arranged to prevent.
		{"GET /api/v1/builds/{name}/vex", s.listVEX,
			onProject(access.ProjectViewer, ofBuild, "reading an artifact's VEX statements")},
		{"POST /api/v1/builds/{name}/vex", s.submitVEX,
			onProject(access.ProjectAdmin, ofBuild, "submitting a VEX statement about an artifact")},

		// Releases.
		{"GET /api/v1/releases", s.listReleases, acrossProjects()},
		{"GET /api/v1/releases/{name}", s.getRelease, onProject(access.ProjectViewer, ofRelease, "reading a release")},

		// Promotions. Asking for a release to land on an environment is a
		// developer's write, the same bar as redeploying — the environment's
		// own requirements are what may still refuse it, through the policy
		// engine rather than through a role. The object that comes back is
		// the record of what was asked and what was decided, which is a
		// viewer's read like every other record.
		{"GET /api/v1/projects/{name}/promotions", s.listProjectPromotions,
			onProject(access.ProjectViewer, ofProject, "reading a project's promotions")},
		{"POST /api/v1/projects/{name}/promotions", s.createPromotion,
			onProject(access.ProjectDeveloper, ofProject, "promoting a release")},
		{"GET /api/v1/promotions/{name}", s.getPromotion,
			onProject(access.ProjectViewer, ofPromotion, "reading a promotion")},

		// Break-glass exceptions. Requesting one is a developer's write — the
		// on-call engineer at 3am — and the escalation ladder is what demands
		// a senior approver, in the handler, because the bar rises with the
		// requested duration rather than with the route. The register is a
		// cross-project read like the decision register; resolving is admin's,
		// since ending a waiver only narrows what is allowed.
		{"POST /api/v1/projects/{name}/exceptions", s.createException,
			onProject(access.ProjectDeveloper, ofProject, "requesting a break-glass exception")},
		{"GET /api/v1/exceptions", s.listExceptions, acrossProjects()},
		{"GET /api/v1/exceptions/{name}", s.getException,
			onProject(access.ProjectViewer, ofException, "reading an exception")},
		{"PATCH /api/v1/exceptions/{name}", s.resolveException,
			onProject(access.ProjectAdmin, ofException, "resolving an exception")},

		// Environments. Moving one to another release is the whole of
		// promotion and rollback, which is what "redeploying" names.
		{"GET /api/v1/environments", s.listEnvironments, acrossProjects()},
		{"GET /api/v1/environments/{name}", s.getEnvironment,
			onProject(access.ProjectViewer, ofEnvironment, "reading an environment")},
		{"PATCH /api/v1/environments/{name}", s.patchEnvironment,
			onProject(access.ProjectDeveloper, ofEnvironment, "redeploying")},
		{"DELETE /api/v1/environments/{name}", s.deleteEnvironment,
			onProject(access.ProjectDeveloper, ofEnvironment, "deleting an environment")},
		{"GET /api/v1/environments/{name}/logs", s.environmentLogs,
			onProject(access.ProjectViewer, ofEnvironment, "reading an environment's logs")},
		{"GET /api/v1/environments/{name}/workload", s.environmentWorkload,
			onProject(access.ProjectViewer, ofEnvironment, "reading an environment's workload")},
		// A Project's workers and scheduled jobs (#78). Reading what they are
		// and how they are getting on is a viewer's read like the workload
		// beside it — a failing nightly job is exactly what a viewer is
		// looking at the project to find out.
		//
		// Starting one off its schedule is a developer's write, the same bar
		// as redeploying and for the same reason: it runs the project's own
		// code, with the project's own credentials, at a moment of somebody's
		// choosing. There is no admin case to make — a person who may push a
		// commit that changes what the job does cannot be meaningfully
		// stopped from running the job.
		{"GET /api/v1/environments/{name}/processes", s.environmentProcesses,
			onProject(access.ProjectViewer, ofEnvironment, "reading an environment's processes")},
		{"GET /api/v1/environments/{name}/processes/{process}/runs", s.processRuns,
			onProject(access.ProjectViewer, ofEnvironment, "reading a scheduled job's runs")},
		{"POST /api/v1/environments/{name}/processes/{process}/runs", s.triggerProcessRun,
			onProject(access.ProjectDeveloper, ofEnvironment, "running a scheduled job")},
		{"GET /api/v1/environments/{name}/metrics", s.environmentMetrics,
			onProject(access.ProjectViewer, ofEnvironment, "reading an environment's metrics")},
		// Operator-only, and a developer needing it is a bug: it answers with
		// the materialized Deployment, whose manifest carries every literal
		// environment variable the project set. docs/AUTH.md says what to do
		// about a developer who needs one — file the missing product surface,
		// rather than widening the role.
		{"GET /api/v1/environments/{name}/objects", s.environmentObjects,
			operatorOnly("reading an environment's Kubernetes objects")},
		{"GET /api/v1/environments/{name}/requests", s.environmentRequests,
			onProject(access.ProjectViewer, ofEnvironment, "reading an environment's requests")},
		{"GET /api/v1/environments/{name}/requests/summary", s.environmentRequestSummary,
			onProject(access.ProjectViewer, ofEnvironment, "reading an environment's requests")},
		{"GET /api/v1/environments/{name}/requests/series", s.environmentRequestSeries,
			onProject(access.ProjectViewer, ofEnvironment, "reading an environment's requests")},
		{"GET /api/v1/environments/{name}/requests/routes", s.environmentRequestRoutes,
			onProject(access.ProjectViewer, ofEnvironment, "reading an environment's requests")},
		{"GET /api/v1/environments/{name}/diagnostics", s.environmentDiagnostics,
			onProject(access.ProjectViewer, ofEnvironment, "reading an environment's diagnostics")},
		{"GET /api/v1/environments/{name}/signals", s.environmentSignals,
			onProject(access.ProjectViewer, ofEnvironment, "reading an environment's signals")},
		// The requirements write is the one row whose project role is not the
		// whole answer, because the answer is not a project role at all: only
		// the environment's owners (spec.owners) or a platform operator may
		// change what it demands, and the table has no kind for "named on the
		// object". So the row admits anyone who may see the environment —
		// viewer, like every environment read — and the handler enforces
		// ownership with a 403 that says who may. What must not happen is a
		// developer role granting the write: deploying into an environment and
		// deciding what it demands are separated on purpose.
		{"PATCH /api/v1/environments/{name}/requirements", s.patchEnvironmentRequirements,
			onProject(access.ProjectViewer, ofEnvironment, "changing an environment's requirements")},
		{"GET /api/v1/environments/{name}/eligibility", s.environmentEligibility,
			onProject(access.ProjectViewer, ofEnvironment, "reading a release's eligibility for an environment")},

		// The observability surface asks across projects and is answered
		// about the caller's own — including the saved queries, where a query
		// naming a project the reader cannot see is not listed at all.
		{"GET /api/v1/logs", s.queryLogs, acrossProjects()},
		{"GET /api/v1/logs/histogram", s.logHistogram, acrossProjects()},
		{"GET /api/v1/logs/facets", s.logFacets, acrossProjects()},
		{"GET /api/v1/logs/patterns", s.logPatterns, acrossProjects()},
		{"GET /api/v1/logs/saved", s.listSavedQueries, acrossProjects()},
		{"POST /api/v1/logs/saved", s.createSavedQuery, anyCaller()},
		{"DELETE /api/v1/logs/saved/{name}", s.deleteSavedQuery, acrossProjects()},

		{"GET /api/v1/events", s.listEvents, acrossProjects()},

		// The decision register. Decisions live in the store rather than the
		// cluster, so the table's project resolvers cannot reach them: the
		// rows admit anyone and hand the handler the caller's scope, and the
		// handlers apply the same rules the guard would — the list filters to
		// visible projects like the audit log, the single reads answer an
		// invisible decision with the not-found a missing one gets, and the
		// replay additionally wants developer on the decision's project,
		// because it writes a decision of its own. The bundle listing is the
		// one governance read here: which bundles exist to require is a fact
		// about the platform, like its settings.
		{"GET /api/v1/decisions", s.listDecisions, acrossProjects()},
		{"GET /api/v1/decisions/{id}", s.getDecision, acrossProjects()},
		{"POST /api/v1/decisions/{id}/replay", s.replayDecision, acrossProjects()},
		{"GET /api/v1/policy/bundles", s.listPolicyBundles,
			operatorOnly("listing the platform's policy bundles")},
		// Compliance describes the platform, not a project: whether the audit
		// log is recording, how long it is kept, and the key evidence is
		// signed under. That is the same shape as GET /settings, and it is
		// the operator's for the same reason.
		{"GET /api/v1/compliance", s.getCompliance, operatorOnly("reading the platform's compliance posture")},
		// The classification inventory is project data, not platform data:
		// which classes and locations *your* environments and claims carry.
		// It filters to the caller's projects like every cross-project read,
		// and an operator's answer is the whole install in one request.
		{"GET /api/v1/compliance/inventory", s.complianceInventory, acrossProjects()},
		// Drift is the same shape of read and the same filtering: what is
		// running right now that no longer meets its environment's bar. It
		// joins the cluster's current state to the decision register, so it
		// is scoped like the register — the caller's own projects, and the
		// whole install for an operator.
		{"GET /api/v1/compliance/drift", s.complianceDrift, acrossProjects()},
		// The criticality mapping, both directions (#141). Same shape and
		// same filtering as the inventory: which of *your* functions are
		// designated and what stands behind them, and which of your
		// environments a third party takes with it. Neither decides
		// anything — the designation is the institution's input, and no
		// route on this platform refuses a deployment because of it.
		{"GET /api/v1/compliance/criticality", s.complianceCriticality, acrossProjects()},
		{"GET /api/v1/compliance/dependents", s.complianceDependents, acrossProjects()},
		// Access recertification. Every one of these is the operator's, and
		// not out of caution: the answer is the whole installation's access
		// in one document, so a member who could read it would learn every
		// account on the platform and every project's membership. "Who has
		// access to shop" is already answerable to shop's own admins,
		// through GET /projects/{name}/members.
		//
		// Deciding is the same requirement as opening, which is deliberate:
		// there is no role between operator and member to give a reviewer,
		// and inventing one to hold a review would be a fourth role in a
		// model that has three. Who was *expected* to review is on the cycle;
		// who actually decided is on every entry and in the audit log.
		{"GET /api/v1/access/identities", s.listIdentities,
			operatorOnly("reading who holds what on the platform")},
		{"GET /api/v1/access/reviews", s.listAccessReviews,
			operatorOnly("reading the platform's access recertifications")},
		{"POST /api/v1/access/reviews", s.openAccessReview,
			operatorOnly("opening an access recertification")},
		{"GET /api/v1/access/reviews/{name}", s.getAccessReview,
			operatorOnly("reading an access recertification")},
		{"PATCH /api/v1/access/reviews/{name}", s.reviewAccess,
			operatorOnly("deciding an access recertification")},

		{"GET /api/v1/audit", s.listAuditRecords, acrossProjects()},
		// Verifying the chain is a statement about the whole log, including
		// the records of platform changes a member never sees.
		{"GET /api/v1/audit/verify", s.verifyAuditChain, operatorOnly("verifying the audit log's chain")},
		{"GET /api/v1/metrics/overview", s.metricsOverview, acrossProjects()},
		{"GET /api/v1/traffic", s.traffic, acrossProjects()},

		{"GET /api/v1/traces", s.listTraces, acrossProjects()},
		{"GET /api/v1/traces/{traceId}", s.getTrace, acrossProjects()},

		// The one route whose body varies by role: the build queue for
		// everyone, the platform's own health for an operator.
		{"GET /api/v1/status", s.getStatus, byRole("reading the platform's status")},

		// Who the caller is, to themselves. It reveals nothing about anyone
		// else, so it needs nothing but a valid token.
		{"GET /api/v1/me", s.getMe, anyCaller()},

		// The operator's own screens. Everything platform-scoped lives under
		// this one prefix and nothing project-scoped does.
		{"GET /api/v1/platform/signals", s.platformSignals, operatorOnly("reading the platform's signals")},
		{"GET /api/v1/platform/nodes", s.platformNodes, operatorOnly("reading the platform's nodes")},
		{"GET /api/v1/platform/workloads", s.platformWorkloads, operatorOnly("reading the platform's workloads")},
		{"GET /api/v1/platform/edge", s.platformEdge, operatorOnly("reading the platform's edge")},
		{"GET /api/v1/platform/storage", s.platformStorage, operatorOnly("reading the platform's storage")},
		{"GET /api/v1/platform/events", s.platformEvents, operatorOnly("reading the platform's cluster events")},
		{"GET /api/v1/platform/ingest", s.platformIngest, operatorOnly("reading the platform's ingest")},

		// How long each class of what the platform keeps is kept, and how far
		// back each class actually goes. The operator's, like every other
		// platform setting — and a route of its own rather than four more
		// fields on /settings, because it is the answer to a question asked
		// from outside the platform, which somebody has to be able to fetch
		// and cite.
		{"GET /api/v1/platform/retention", s.getRetention,
			operatorOnly("reading the platform's retention")},
		{"PATCH /api/v1/platform/retention", s.patchRetention,
			operatorOnly("changing the platform's retention")},

		// The backup. Reading what an archive would carry is already the
		// platform's shape — how many projects, which secrets, which database —
		// and taking one hands over every credential the installation holds, so
		// both are the operator's and neither is anybody else's. There is no
		// restore route: a restore happens into a cluster whose accounts are
		// gone, so there is nobody left to authenticate. See internal/api/backup.go.
		{"GET /api/v1/platform/backup", s.getBackup, operatorOnly("reading what a platform backup would carry")},
		{"POST /api/v1/platform/backup", s.createBackup, operatorOnly("exporting the platform's state")},

		// Settings carry the base domain, the issuer and the gateway address,
		// so even reading them is the operator's.
		{"GET /api/v1/settings", s.getSettings, operatorOnly("reading the platform's settings")},
		{"PATCH /api/v1/settings", s.patchSettings, operatorOnly("changing the platform's settings")},

		{"GET /api/v1/updates", s.listUpdates, operatorOnly("reading the platform's updates")},
		{"POST /api/v1/updates", s.createUpdate, operatorOnly("upgrading the platform")},
		{"GET /api/v1/updates/{name}", s.getUpdate, operatorOnly("reading a platform update")},
		{"GET /api/v1/updates/{name}/logs", s.updateLogs, operatorOnly("reading a platform update's logs")},

		// Connections hold the platform's credentials to everything else, so
		// every one of these is the operator's — except the two the
		// create-a-project form is filled in from. The list is the picker: it
		// answers an operator with the connections themselves and everybody
		// else with the three things a dropdown needs — name, capabilities,
		// readiness. The repository listing is the next field of the same
		// form, and it is the caller's own account that would otherwise be
		// typing the repository's name into it. Neither creates, edits, tests
		// or deletes anything, and neither can reach a credential: the second
		// answers what the stored credential can see, never the credential.
		{"GET /api/v1/connections", s.listConnections, byRole("choosing a connection")},
		{"GET /api/v1/connections/{name}/repositories", s.listConnectionRepositories, anyCaller()},
		// The third field of the same form, and the one that is worth being
		// wrong about early: it reads the repository the way a build would
		// and says what the platform makes of it, so a root directory one
		// level off is a sentence on the form rather than a failed build
		// five minutes later. It writes nothing and reaches no credential.
		{"POST /api/v1/connections/{name}/detect", s.detectRepository, anyCaller()},
		{"POST /api/v1/connections", s.createConnection, operatorOnly("adding a connection")},
		{"POST /api/v1/connections/test", s.testConnection, operatorOnly("testing a connection")},
		{"GET /api/v1/connections/{name}", s.getConnection, operatorOnly("reading a connection")},
		{"PATCH /api/v1/connections/{name}", s.patchConnection, operatorOnly("changing a connection")},
		{"DELETE /api/v1/connections/{name}", s.deleteConnection, operatorOnly("deleting a connection")},

		// Domains belong to an environment, and so to its project.
		{"GET /api/v1/domains", s.listDomains, acrossProjects()},
		{"POST /api/v1/domains", s.createDomain,
			onProject(access.ProjectDeveloper, ofEnvironmentInBody, "attaching a domain")},
		{"GET /api/v1/domains/{name}", s.getDomain, onProject(access.ProjectViewer, ofDomain, "reading a domain")},
		{"DELETE /api/v1/domains/{name}", s.deleteDomain,
			onProject(access.ProjectDeveloper, ofDomain, "removing a domain")},

		// Claims name their project outright.
		{"GET /api/v1/claims", s.listClaims, acrossProjects()},
		{"POST /api/v1/claims", s.createClaim,
			onProject(access.ProjectDeveloper, ofProjectInBody, "claiming a resource")},
		{"GET /api/v1/claims/{name}", s.getClaim, onProject(access.ProjectViewer, ofClaim, "reading a resource claim")},
		{"DELETE /api/v1/claims/{name}", s.deleteClaim,
			onProject(access.ProjectDeveloper, ofClaim, "deleting a resource claim")},

		// Anything else under the API prefix is a 404 rather than a
		// fall-through, and it is still a 404 only after the caller has been
		// identified: an anonymous request should not be able to map the
		// API's shape.
		{"/", s.noSuchEndpoint, anyCaller()},
	}
}

func (s *Server) noSuchEndpoint(w http.ResponseWriter, req *http.Request) {
	writeJSON(w, http.StatusNotFound, errorBody{
		Error: fmt.Sprintf("no such endpoint: %s %s", req.Method, req.URL.Path),
	})
}

// projectResolver works out which Project a request is about, and which object
// the request addressed — the one a caller with no role on it is told does not
// exist.
type projectResolver struct {
	// Resource is the plural resource the request addresses, spelled as the
	// API server spells it, so that the not-found this produces is the same
	// sentence a genuinely missing object produces.
	Resource string
	// Resolve answers the project's name and the addressed object's. An empty
	// project means the request names none that exists, which is not by itself
	// a refusal: an operator holds admin regardless, and for everyone else it
	// resolves to no role and so to a not-found. An empty target means the
	// request named nothing at all — a body with no project in it — and the
	// handler is left to say so, which it does with a 400.
	Resolve func(s *Server, req *http.Request) (project string, target string, err error)
}

// ofProject is the path itself: /projects/{name}.
var ofProject = projectResolver{
	Resource: "projects",
	Resolve: func(_ *Server, req *http.Request) (string, string, error) {
		name := req.PathValue("name")
		return name, name, nil
	},
}

// The objects that name their project outright. Each reads the object once and
// leaves it where the handler's own s.get will find it, so the request costs
// one read rather than two.
var (
	ofBuild = objectResolver("builds", func() client.Object { return &kitchenv1alpha1.Build{} },
		func(obj client.Object) string { return obj.(*kitchenv1alpha1.Build).Spec.ProjectRef.Name })
	ofRelease = objectResolver("releases", func() client.Object { return &kitchenv1alpha1.Release{} },
		func(obj client.Object) string { return obj.(*kitchenv1alpha1.Release).Spec.ProjectRef.Name })
	ofEnvironment = objectResolver("environments", func() client.Object { return &kitchenv1alpha1.Environment{} },
		func(obj client.Object) string { return obj.(*kitchenv1alpha1.Environment).Spec.ProjectRef.Name })
	ofClaim = objectResolver("resourceclaims", func() client.Object { return &kitchenv1alpha1.ResourceClaim{} },
		func(obj client.Object) string { return obj.(*kitchenv1alpha1.ResourceClaim).Spec.ProjectRef.Name })
	ofPromotion = objectResolver("promotions", func() client.Object { return &kitchenv1alpha1.Promotion{} },
		func(obj client.Object) string { return obj.(*kitchenv1alpha1.Promotion).Spec.ProjectRef.Name })
	ofException = objectResolver("exceptions", func() client.Object { return &kitchenv1alpha1.Exception{} },
		func(obj client.Object) string { return obj.(*kitchenv1alpha1.Exception).Spec.ProjectRef.Name })
)

// ofDomain is the one path-addressed object that does not name a project. A
// Domain names an Environment — a hostname is attached to something running,
// not to a project — so the project is one hop further away, and both objects
// are kept for the handler.
var ofDomain = projectResolver{
	Resource: "domains",
	Resolve: func(s *Server, req *http.Request) (string, string, error) {
		name := req.PathValue("name")
		domain := &kitchenv1alpha1.Domain{}
		if err := s.get(req.Context(), name, domain); err != nil {
			return "", name, err
		}
		keepResolved(req.Context(), domain)

		env := &kitchenv1alpha1.Environment{}
		if err := s.get(req.Context(), domain.Spec.EnvironmentRef.Name, env); err != nil {
			if apierrors.IsNotFound(err) {
				// A domain whose environment is gone belongs to nobody, and
				// only an operator can still see it.
				return "", name, nil
			}
			return "", name, err
		}
		keepResolved(req.Context(), env)
		return env.Spec.ProjectRef.Name, name, nil
	},
}

// objectResolver builds the resolver for a path-addressed object that carries
// its project in its spec.
func objectResolver(
	resource string,
	empty func() client.Object,
	projectOf func(client.Object) string,
) projectResolver {
	return projectResolver{
		Resource: resource,
		Resolve: func(s *Server, req *http.Request) (string, string, error) {
			name := req.PathValue("name")
			obj := empty()
			if err := s.get(req.Context(), name, obj); err != nil {
				return "", name, err
			}
			keepResolved(req.Context(), obj)
			return projectOf(obj), name, nil
		},
	}
}

// ofProjectInBody reads the project a write names in its own body.
var ofProjectInBody = fromBody("projects", "project", nil)

// ofEnvironmentInBody is the same for a write that names an environment, which
// is how a domain says which project it is for.
var ofEnvironmentInBody = fromBody("environments", "environment",
	func(s *Server, req *http.Request, name string) (string, error) {
		env := &kitchenv1alpha1.Environment{}
		if err := s.get(req.Context(), name, env); err != nil {
			if apierrors.IsNotFound(err) {
				return "", nil
			}
			return "", err
		}
		keepResolved(req.Context(), env)
		return env.Spec.ProjectRef.Name, nil
	})

// fromBody resolves a project out of a JSON request body, putting the body
// back so the handler decodes exactly what the caller sent.
//
// A body that is not readable JSON, or that names nothing, resolves to no
// target at all: the handler refuses such a request with a 400 that says which
// field is missing, and that is a better answer than anything the guard could
// give. Nothing is written on that path — both handlers that take a project in
// their body validate it before they touch the cluster.
func fromBody(
	resource, field string,
	project func(s *Server, req *http.Request, name string) (string, error),
) projectResolver {
	return projectResolver{
		Resource: resource,
		Resolve: func(s *Server, req *http.Request) (string, string, error) {
			raw, err := io.ReadAll(io.LimitReader(req.Body, maxRequestBody))
			if err != nil {
				return "", "", err
			}
			req.Body = io.NopCloser(bytes.NewReader(raw))

			values := map[string]any{}
			if err := json.Unmarshal(raw, &values); err != nil {
				return "", "", nil
			}
			name, _ := values[field].(string)
			if name = strings.TrimSpace(name); name == "" {
				return "", "", nil
			}
			if project == nil {
				return name, name, nil
			}
			resolved, err := project(s, req, name)
			return resolved, name, err
		},
	}
}

// guard wraps a handler in its requirement. It runs inside the mux, where
// req.PathValue is filled in, and inside the token check, where the caller is
// known.
func (s *Server) guard(requires requirement, handler http.HandlerFunc) http.HandlerFunc {
	return func(w http.ResponseWriter, req *http.Request) {
		caller, _ := CallerFrom(req.Context())
		kitchen := kitchenFrom(req.Context())
		platform := access.PlatformRoleFor(caller.access(), kitchen)
		req = req.WithContext(withPlatformRole(req.Context(), platform))

		switch requires.Kind {
		case requireAuthenticated:
			// The token was the whole requirement, and it was checked before
			// this ever ran.

		case requireOperator:
			if !platform.AtLeast(access.PlatformOperator) {
				if kitchen == nil || len(kitchen.Spec.Access.Operators) == 0 {
					// An installation whose operator list has not been written
					// yet has no operators, so the whole platform surface is
					// refused to everybody. That is the safe direction and it
					// is somebody else's job to fix (the upgrade seeds the
					// list); what it must not be is a mystery, so it is said
					// out loud rather than left to be inferred from a 403.
					s.log().Info("refusing a platform operation: this installation lists no operators at all",
						"path", req.URL.Path, "caller", callerName(caller))
				}
				forbidden(w, fmt.Sprintf("%s needs the operator role; you are a %s",
					requires.Doing, platform))
				return
			}

		case requireProjectRole:
			if !s.allowedOnProject(w, &req, requires, caller, kitchen) {
				return
			}

		case requireVisibleProjects:
			scope, err := s.scopeFor(req.Context(), caller, kitchen, platform)
			if err != nil {
				s.writeError(w, err)
				return
			}
			req = req.WithContext(withScope(req.Context(), scope))

		case requireRoleShapedBody:
			// The platform role is in the context above, and the handler
			// shapes its own body from it. The visible scope goes in as well,
			// because a body that varies by role still has rows in it that
			// name projects — GET /status carries the build queue, which is
			// everybody's as a queue and nobody else's as a list of names.
			// Resolving it here rather than in the handler keeps "what may
			// this caller see" in the one place that answers it.
			scope, err := s.scopeFor(req.Context(), caller, kitchen, platform)
			if err != nil {
				s.writeError(w, err)
				return
			}
			req = req.WithContext(withScope(req.Context(), scope))
		}

		handler(w, req)
	}
}

// allowedOnProject resolves the request's project, decides, and reports
// whether the handler may run. It answers the request itself when it may not.
func (s *Server) allowedOnProject(
	w http.ResponseWriter,
	req **http.Request,
	requires requirement,
	caller Caller,
	kitchen *kitchenv1alpha1.Kitchen,
) bool {
	ctx := withResolved((*req).Context())
	*req = (*req).WithContext(ctx)

	name, target, err := requires.Project.Resolve(s, *req)
	if err != nil {
		// The object the path named is not there, or the cluster could not be
		// asked. Either way it is the same answer for everybody.
		s.writeError(w, err)
		return false
	}

	var project *kitchenv1alpha1.Project
	if name != "" {
		found := &kitchenv1alpha1.Project{}
		switch err := s.get(ctx, name, found); {
		case err == nil:
			keepResolved(ctx, found)
			project = found
		case apierrors.IsNotFound(err):
			// A dangling reference. Nobody holds a role on a project that is
			// not there, which resolves below to a not-found — except for an
			// operator, who holds admin on every project and gets the
			// handler's own account of the mess.
		default:
			s.writeError(w, err)
			return false
		}
	}

	role := access.ProjectRoleFor(caller.access(), kitchen, project)
	if !role.AtLeast(access.ProjectViewer) {
		if target == "" {
			// The request named nothing at all. The handler says which field
			// it wanted, which is more use than a not-found for "".
			return true
		}
		// No role at all: the object is not one this caller may know exists,
		// so they are told it does not — in the same words the API server
		// uses for one that genuinely is not there.
		s.writeError(w, apierrors.NewNotFound(
			schema.GroupResource{Group: kitchenv1alpha1.GroupVersion.Group, Resource: requires.Project.Resource},
			target))
		return false
	}
	if !role.AtLeast(requires.Role) {
		forbidden(w, fmt.Sprintf("you have %s on %s; %s needs %s", role, name, requires.Doing, requires.Role))
		return false
	}
	return true
}

// forbidden answers a caller who is who they say they are and may not do this.
//
// The message follows the rule kitchen.validate follows for the chart's
// guards: say what is wrong *and* what would fix it. Every one of them is
// built from the table's own words, so no handler carries a refusal string.
func forbidden(w http.ResponseWriter, reason string) {
	writeJSON(w, http.StatusForbidden, errorBody{Error: reason})
}

// visibleProject answers the request itself when the caller may not see the
// project a `?project=` names, and reports whether the handler may go on.
//
// The answer is the not-found a project that is not there produces, in the
// same words: a caller who cannot see `billing` and a caller on a platform
// with no `billing` are told the same thing.
func (s *Server) visibleProject(w http.ResponseWriter, req *http.Request, name string) bool {
	if name == "" || scopeFrom(req.Context()).allows(name) {
		return true
	}
	s.writeError(w, apierrors.NewNotFound(
		schema.GroupResource{Group: kitchenv1alpha1.GroupVersion.Group, Resource: "projects"}, name))
	return false
}

// scopeFor is the set of projects a cross-project read may answer about.
func (s *Server) scopeFor(
	ctx context.Context,
	caller Caller,
	kitchen *kitchenv1alpha1.Kitchen,
	platform access.PlatformRole,
) (projectScope, error) {
	if platform.AtLeast(access.PlatformOperator) {
		// Everything, and nothing to list: an operator sees every project,
		// present and future, which is access.ProjectRoleFor's rule and not a
		// second copy of it.
		return projectScope{all: true}, nil
	}
	list := &kitchenv1alpha1.ProjectList{}
	if err := s.Client.List(ctx, list, client.InNamespace(s.Namespace)); err != nil {
		return projectScope{}, err
	}
	scope := projectScope{visible: map[string]struct{}{}}
	for _, project := range access.VisibleProjects(caller.access(), kitchen, list.Items) {
		scope.visible[project.Name] = struct{}{}
	}
	for i := range list.Items {
		if _, ok := scope.visible[list.Items[i].Name]; !ok {
			scope.hidden = append(scope.hidden, list.Items[i].Name)
		}
	}
	return scope, nil
}

// projectScope is which projects a cross-project read may answer about: every
// one for an operator, and otherwise the ones the caller holds a role on.
//
// A row belonging to no project at all — a cluster log line, an audit record
// about the platform itself, an activity entry the reconcilers wrote — belongs
// to the platform, so only an operator sees it. That is what makes `allows("")`
// false rather than true.
type projectScope struct {
	all     bool
	visible map[string]struct{}
	// hidden is the other half of the same list: the projects this caller may
	// not see, by name. It is kept because one read has to go the other way
	// round — a saved query must not be listed when it *mentions* a project
	// the reader cannot see, and answering that needs the names to look for.
	// Both halves come out of the one list scopeFor already read.
	hidden []string
}

func (p projectScope) allows(project string) bool {
	if p.all {
		return true
	}
	if project == "" {
		return false
	}
	_, ok := p.visible[project]
	return ok
}

// empty reports a caller who can see nothing at all, which every cross-project
// read answers without asking the store anything.
func (p projectScope) empty() bool { return !p.all && len(p.visible) == 0 }

// names is the visible projects, sorted, for the reads that push the scope
// into the store rather than filtering what comes back.
func (p projectScope) names() []string {
	out := make([]string, 0, len(p.visible))
	for name := range p.visible {
		out = append(out, name)
	}
	sort.Strings(out)
	return out
}

// The three things the guard leaves in the request's context: the caller's
// platform role, the scope of a cross-project read, and whatever objects were
// read to resolve the project.

type (
	platformRoleKey struct{}
	scopeKey        struct{}
	resolvedKey     struct{}
)

func withPlatformRole(ctx context.Context, role access.PlatformRole) context.Context {
	return context.WithValue(ctx, platformRoleKey{}, role)
}

// platformRoleFrom is the caller's platform role. It is set for every request
// that reached a handler, and PlatformRoleNone — which satisfies nothing — is
// what a caller nobody resolved reads as.
func platformRoleFrom(ctx context.Context) access.PlatformRole {
	role, _ := ctx.Value(platformRoleKey{}).(access.PlatformRole)
	return role
}

func withScope(ctx context.Context, scope projectScope) context.Context {
	return context.WithValue(ctx, scopeKey{}, scope)
}

// scopeFrom is the visible-project scope a filtered route was given. A route
// the table did not mark as filtered has none, and reads as "nothing visible"
// rather than as "everything" — the safe direction for a handler that started
// filtering without its row being updated.
func scopeFrom(ctx context.Context) projectScope {
	scope, _ := ctx.Value(scopeKey{}).(projectScope)
	return scope
}

// resolvedObjects is what the guard read to answer "which project is this
// about", kept for the length of the request so the handler does not read the
// same object again. It is a pointer in the context because the resolver adds
// to it after the context is built.
type resolvedObjects struct{ objects []client.Object }

func withResolved(ctx context.Context) context.Context {
	return context.WithValue(ctx, resolvedKey{}, &resolvedObjects{})
}

// keepResolved offers an object the guard has just read to the handler that
// will want it.
func keepResolved(ctx context.Context, obj client.Object) {
	if kept, ok := ctx.Value(resolvedKey{}).(*resolvedObjects); ok {
		kept.objects = append(kept.objects, obj)
	}
}

// resolvedObject fills `into` from what the guard already read, and reports
// whether it could.
//
// It matches on the concrete type and the name, which is the whole of what
// s.get is asked for — everything the API reads by name lives in the one
// platform namespace. The copy is deep so that a handler which edits what it
// read (a PATCH, a delete) cannot reach back into another handler's object.
func resolvedObject(ctx context.Context, name string, into client.Object) bool {
	kept, ok := ctx.Value(resolvedKey{}).(*resolvedObjects)
	if !ok {
		return false
	}
	target := reflect.ValueOf(into)
	for _, obj := range kept.objects {
		if obj.GetName() != name || reflect.TypeOf(obj) != target.Type() {
			continue
		}
		target.Elem().Set(reflect.ValueOf(obj.DeepCopyObject()).Elem())
		return true
	}
	return false
}
