/**
 * The API's enforcement table, as the dashboard's copy of it.
 *
 * Generated by hack/gen-ui-policy from internal/api/policy.go. DO NOT EDIT.
 * Run `make ui-policy` to refresh it; CI fails when the checked-in copy
 * and a fresh run differ.
 *
 * It is data and no logic, on purpose. The questions the dashboard actually
 * asks — may this person redeploy, and what do I say when they may not — are
 * answered by the hand-written helper next to it in ./policy, which is where
 * anything that has to be reasoned about belongs. What is here is only what
 * the API's own table says, so that the two cannot disagree.
 */

/** The platform roles, weakest first: exactly one per account. */
export const PLATFORM_ROLES = ["member", "operator"] as const;
export type PlatformRole = (typeof PLATFORM_ROLES)[number];

/** The project roles, weakest first: one per account, per project. */
export const PROJECT_ROLES = ["viewer", "developer", "admin"] as const;
export type ProjectRole = (typeof PROJECT_ROLES)[number];

/**
 * What a route asks of its caller.
 *
 * - "authenticated" — any valid token. The caller's own identity is the whole of it.
 * - "operator" — the platform's operators alone.
 * - "projectRole" — at least `role` on the project the request is about.
 * - "visibleProjects" — any valid token, and the answer is narrowed to the caller's own
 *   projects. Admission is never the question here; completeness is.
 * - "roleShapedBody" — any valid token, and the *body* varies by the caller's platform
 *   role. Which parts are missing is the handler's own business and is not
 *   something this table can say.
 */
export const REQUIREMENT_KINDS = ["authenticated", "operator", "projectRole", "visibleProjects", "roleShapedBody"] as const;
export type RequirementKind = (typeof REQUIREMENT_KINDS)[number];

/** One row's answer to "who may call this". */
export interface Requirement {
  kind: RequirementKind;
  /** The project role wanted, set only for "projectRole". */
  role?: ProjectRole;
  /**
   * The operation in the words a refusal uses — "redeploying", "changing the
   * platform's settings" — so a disabled control can be explained in the same
   * vocabulary the API's own 403 uses. Absent for the kinds that never refuse
   * a caller holding a valid token.
   */
  doing?: string;
}

/** Every pattern the API serves, spelled as the API's own table spells it. */
export type Route =
  | "GET /api/v1/projects"
  | "POST /api/v1/projects"
  | "GET /api/v1/projects/{name}"
  | "PATCH /api/v1/projects/{name}"
  | "PATCH /api/v1/projects/{name}/env"
  | "DELETE /api/v1/projects/{name}"
  | "GET /api/v1/projects/{name}/builds"
  | "POST /api/v1/projects/{name}/builds"
  | "GET /api/v1/projects/{name}/releases"
  | "GET /api/v1/projects/{name}/environments"
  | "GET /api/v1/projects/{name}/audit-pack"
  | "GET /api/v1/projects/{name}/members"
  | "POST /api/v1/projects/{name}/members"
  | "PATCH /api/v1/projects/{name}/members"
  | "DELETE /api/v1/projects/{name}/members"
  | "GET /api/v1/projects/{name}/keys"
  | "POST /api/v1/projects/{name}/keys"
  | "DELETE /api/v1/projects/{name}/keys/{key}"
  | "GET /api/v1/builds"
  | "GET /api/v1/builds/{name}"
  | "POST /api/v1/builds/{name}/cancel"
  | "GET /api/v1/builds/{name}/logs"
  | "GET /api/v1/builds/{name}/attestations"
  | "POST /api/v1/builds/{name}/gates"
  | "GET /api/v1/builds/{name}/vex"
  | "POST /api/v1/builds/{name}/vex"
  | "GET /api/v1/releases"
  | "GET /api/v1/releases/{name}"
  | "GET /api/v1/releases/{name}/config-diff"
  | "GET /api/v1/projects/{name}/promotions"
  | "POST /api/v1/projects/{name}/promotions"
  | "GET /api/v1/promotions/{name}"
  | "POST /api/v1/projects/{name}/exceptions"
  | "GET /api/v1/exceptions"
  | "GET /api/v1/exceptions/{name}"
  | "PATCH /api/v1/exceptions/{name}"
  | "GET /api/v1/environments"
  | "GET /api/v1/environments/{name}"
  | "PATCH /api/v1/environments/{name}"
  | "DELETE /api/v1/environments/{name}"
  | "GET /api/v1/environments/{name}/logs"
  | "GET /api/v1/environments/{name}/workload"
  | "GET /api/v1/environments/{name}/processes"
  | "GET /api/v1/environments/{name}/processes/{process}/runs"
  | "POST /api/v1/environments/{name}/processes/{process}/runs"
  | "GET /api/v1/environments/{name}/metrics"
  | "GET /api/v1/environments/{name}/objects"
  | "GET /api/v1/environments/{name}/requests"
  | "GET /api/v1/environments/{name}/requests/summary"
  | "GET /api/v1/environments/{name}/requests/series"
  | "GET /api/v1/environments/{name}/requests/routes"
  | "GET /api/v1/environments/{name}/diagnostics"
  | "GET /api/v1/environments/{name}/signals"
  | "PATCH /api/v1/environments/{name}/requirements"
  | "GET /api/v1/environments/{name}/eligibility"
  | "GET /api/v1/logs"
  | "GET /api/v1/logs/histogram"
  | "GET /api/v1/logs/facets"
  | "GET /api/v1/logs/patterns"
  | "GET /api/v1/logs/saved"
  | "POST /api/v1/logs/saved"
  | "DELETE /api/v1/logs/saved/{name}"
  | "GET /api/v1/events"
  | "GET /api/v1/decisions"
  | "GET /api/v1/decisions/{id}"
  | "POST /api/v1/decisions/{id}/replay"
  | "GET /api/v1/policy/bundles"
  | "GET /api/v1/compliance"
  | "GET /api/v1/compliance/inventory"
  | "GET /api/v1/compliance/drift"
  | "GET /api/v1/compliance/criticality"
  | "GET /api/v1/compliance/dependents"
  | "GET /api/v1/access/identities"
  | "GET /api/v1/access/reviews"
  | "POST /api/v1/access/reviews"
  | "GET /api/v1/access/reviews/{name}"
  | "PATCH /api/v1/access/reviews/{name}"
  | "GET /api/v1/audit"
  | "GET /api/v1/audit/verify"
  | "GET /api/v1/metrics/overview"
  | "GET /api/v1/traffic"
  | "GET /api/v1/traces"
  | "GET /api/v1/traces/{traceId}"
  | "GET /api/v1/status"
  | "GET /api/v1/me"
  | "GET /api/v1/platform/signals"
  | "GET /api/v1/platform/nodes"
  | "GET /api/v1/platform/workloads"
  | "GET /api/v1/platform/edge"
  | "GET /api/v1/platform/storage"
  | "GET /api/v1/platform/events"
  | "GET /api/v1/platform/ingest"
  | "GET /api/v1/platform/retention"
  | "PATCH /api/v1/platform/retention"
  | "GET /api/v1/platform/backup"
  | "POST /api/v1/platform/backup"
  | "GET /api/v1/settings"
  | "PATCH /api/v1/settings"
  | "GET /api/v1/updates"
  | "POST /api/v1/updates"
  | "GET /api/v1/updates/{name}"
  | "GET /api/v1/updates/{name}/logs"
  | "GET /api/v1/connections"
  | "GET /api/v1/connections/{name}/repositories"
  | "POST /api/v1/connections/{name}/detect"
  | "POST /api/v1/connections"
  | "POST /api/v1/connections/test"
  | "GET /api/v1/connections/{name}"
  | "PATCH /api/v1/connections/{name}"
  | "DELETE /api/v1/connections/{name}"
  | "GET /api/v1/domains"
  | "POST /api/v1/domains"
  | "GET /api/v1/domains/{name}"
  | "DELETE /api/v1/domains/{name}"
  | "GET /api/v1/claims"
  | "POST /api/v1/claims"
  | "GET /api/v1/claims/{name}"
  | "DELETE /api/v1/claims/{name}"
  | "/"
;

/**
 * What every route requires. Keyed by the pattern, so a lookup is the same
 * string the API registers the route under.
 */
export const POLICY: Readonly<Record<Route, Requirement>> = {
  "GET /api/v1/projects": { kind: "visibleProjects" },
  "POST /api/v1/projects": { kind: "authenticated" },
  "GET /api/v1/projects/{name}": { kind: "projectRole", role: "viewer", doing: "reading a project" },
  "PATCH /api/v1/projects/{name}": { kind: "projectRole", role: "admin", doing: "changing a project's settings" },
  "PATCH /api/v1/projects/{name}/env": { kind: "projectRole", role: "developer", doing: "changing a project's environment variables" },
  "DELETE /api/v1/projects/{name}": { kind: "projectRole", role: "admin", doing: "deleting a project" },
  "GET /api/v1/projects/{name}/builds": { kind: "projectRole", role: "viewer", doing: "reading a project's builds" },
  "POST /api/v1/projects/{name}/builds": { kind: "projectRole", role: "developer", doing: "starting a build" },
  "GET /api/v1/projects/{name}/releases": { kind: "projectRole", role: "viewer", doing: "reading a project's releases" },
  "GET /api/v1/projects/{name}/environments": { kind: "projectRole", role: "viewer", doing: "reading a project's environments" },
  "GET /api/v1/projects/{name}/audit-pack": { kind: "operator", doing: "exporting a project's audit pack" },
  "GET /api/v1/projects/{name}/members": { kind: "projectRole", role: "viewer", doing: "reading a project's members" },
  "POST /api/v1/projects/{name}/members": { kind: "projectRole", role: "admin", doing: "adding somebody to a project" },
  "PATCH /api/v1/projects/{name}/members": { kind: "projectRole", role: "admin", doing: "changing somebody's role on a project" },
  "DELETE /api/v1/projects/{name}/members": { kind: "projectRole", role: "admin", doing: "removing somebody from a project" },
  "GET /api/v1/projects/{name}/keys": { kind: "projectRole", role: "viewer", doing: "reading a project's CI keys" },
  "POST /api/v1/projects/{name}/keys": { kind: "projectRole", role: "admin", doing: "issuing a CI key for a project" },
  "DELETE /api/v1/projects/{name}/keys/{key}": { kind: "projectRole", role: "admin", doing: "revoking a project's CI key" },
  "GET /api/v1/builds": { kind: "visibleProjects" },
  "GET /api/v1/builds/{name}": { kind: "projectRole", role: "viewer", doing: "reading a build" },
  "POST /api/v1/builds/{name}/cancel": { kind: "projectRole", role: "developer", doing: "cancelling a build" },
  "GET /api/v1/builds/{name}/logs": { kind: "projectRole", role: "viewer", doing: "reading a build's logs" },
  "GET /api/v1/builds/{name}/attestations": { kind: "projectRole", role: "viewer", doing: "reading a build's attestations" },
  "POST /api/v1/builds/{name}/gates": { kind: "projectRole", role: "developer", doing: "submitting a quality gate result" },
  "GET /api/v1/builds/{name}/vex": { kind: "projectRole", role: "viewer", doing: "reading an artifact's VEX statements" },
  "POST /api/v1/builds/{name}/vex": { kind: "projectRole", role: "admin", doing: "submitting a VEX statement about an artifact" },
  "GET /api/v1/releases": { kind: "visibleProjects" },
  "GET /api/v1/releases/{name}": { kind: "projectRole", role: "viewer", doing: "reading a release" },
  "GET /api/v1/releases/{name}/config-diff": { kind: "projectRole", role: "viewer", doing: "comparing two releases' configuration" },
  "GET /api/v1/projects/{name}/promotions": { kind: "projectRole", role: "viewer", doing: "reading a project's promotions" },
  "POST /api/v1/projects/{name}/promotions": { kind: "projectRole", role: "developer", doing: "promoting a release" },
  "GET /api/v1/promotions/{name}": { kind: "projectRole", role: "viewer", doing: "reading a promotion" },
  "POST /api/v1/projects/{name}/exceptions": { kind: "projectRole", role: "developer", doing: "requesting a break-glass exception" },
  "GET /api/v1/exceptions": { kind: "visibleProjects" },
  "GET /api/v1/exceptions/{name}": { kind: "projectRole", role: "viewer", doing: "reading an exception" },
  "PATCH /api/v1/exceptions/{name}": { kind: "projectRole", role: "admin", doing: "resolving an exception" },
  "GET /api/v1/environments": { kind: "visibleProjects" },
  "GET /api/v1/environments/{name}": { kind: "projectRole", role: "viewer", doing: "reading an environment" },
  "PATCH /api/v1/environments/{name}": { kind: "projectRole", role: "developer", doing: "redeploying" },
  "DELETE /api/v1/environments/{name}": { kind: "projectRole", role: "developer", doing: "deleting an environment" },
  "GET /api/v1/environments/{name}/logs": { kind: "projectRole", role: "viewer", doing: "reading an environment's logs" },
  "GET /api/v1/environments/{name}/workload": { kind: "projectRole", role: "viewer", doing: "reading an environment's workload" },
  "GET /api/v1/environments/{name}/processes": { kind: "projectRole", role: "viewer", doing: "reading an environment's processes" },
  "GET /api/v1/environments/{name}/processes/{process}/runs": { kind: "projectRole", role: "viewer", doing: "reading a scheduled job's runs" },
  "POST /api/v1/environments/{name}/processes/{process}/runs": { kind: "projectRole", role: "developer", doing: "running a scheduled job" },
  "GET /api/v1/environments/{name}/metrics": { kind: "projectRole", role: "viewer", doing: "reading an environment's metrics" },
  "GET /api/v1/environments/{name}/objects": { kind: "operator", doing: "reading an environment's Kubernetes objects" },
  "GET /api/v1/environments/{name}/requests": { kind: "projectRole", role: "viewer", doing: "reading an environment's requests" },
  "GET /api/v1/environments/{name}/requests/summary": { kind: "projectRole", role: "viewer", doing: "reading an environment's requests" },
  "GET /api/v1/environments/{name}/requests/series": { kind: "projectRole", role: "viewer", doing: "reading an environment's requests" },
  "GET /api/v1/environments/{name}/requests/routes": { kind: "projectRole", role: "viewer", doing: "reading an environment's requests" },
  "GET /api/v1/environments/{name}/diagnostics": { kind: "projectRole", role: "viewer", doing: "reading an environment's diagnostics" },
  "GET /api/v1/environments/{name}/signals": { kind: "projectRole", role: "viewer", doing: "reading an environment's signals" },
  "PATCH /api/v1/environments/{name}/requirements": { kind: "projectRole", role: "viewer", doing: "changing an environment's requirements" },
  "GET /api/v1/environments/{name}/eligibility": { kind: "projectRole", role: "viewer", doing: "reading a release's eligibility for an environment" },
  "GET /api/v1/logs": { kind: "visibleProjects" },
  "GET /api/v1/logs/histogram": { kind: "visibleProjects" },
  "GET /api/v1/logs/facets": { kind: "visibleProjects" },
  "GET /api/v1/logs/patterns": { kind: "visibleProjects" },
  "GET /api/v1/logs/saved": { kind: "visibleProjects" },
  "POST /api/v1/logs/saved": { kind: "authenticated" },
  "DELETE /api/v1/logs/saved/{name}": { kind: "visibleProjects" },
  "GET /api/v1/events": { kind: "visibleProjects" },
  "GET /api/v1/decisions": { kind: "visibleProjects" },
  "GET /api/v1/decisions/{id}": { kind: "visibleProjects" },
  "POST /api/v1/decisions/{id}/replay": { kind: "visibleProjects" },
  "GET /api/v1/policy/bundles": { kind: "operator", doing: "listing the platform's policy bundles" },
  "GET /api/v1/compliance": { kind: "operator", doing: "reading the platform's compliance posture" },
  "GET /api/v1/compliance/inventory": { kind: "visibleProjects" },
  "GET /api/v1/compliance/drift": { kind: "visibleProjects" },
  "GET /api/v1/compliance/criticality": { kind: "visibleProjects" },
  "GET /api/v1/compliance/dependents": { kind: "visibleProjects" },
  "GET /api/v1/access/identities": { kind: "operator", doing: "reading who holds what on the platform" },
  "GET /api/v1/access/reviews": { kind: "operator", doing: "reading the platform's access recertifications" },
  "POST /api/v1/access/reviews": { kind: "operator", doing: "opening an access recertification" },
  "GET /api/v1/access/reviews/{name}": { kind: "operator", doing: "reading an access recertification" },
  "PATCH /api/v1/access/reviews/{name}": { kind: "operator", doing: "deciding an access recertification" },
  "GET /api/v1/audit": { kind: "visibleProjects" },
  "GET /api/v1/audit/verify": { kind: "operator", doing: "verifying the audit log's chain" },
  "GET /api/v1/metrics/overview": { kind: "visibleProjects" },
  "GET /api/v1/traffic": { kind: "visibleProjects" },
  "GET /api/v1/traces": { kind: "visibleProjects" },
  "GET /api/v1/traces/{traceId}": { kind: "visibleProjects" },
  "GET /api/v1/status": { kind: "roleShapedBody", doing: "reading the platform's status" },
  "GET /api/v1/me": { kind: "authenticated" },
  "GET /api/v1/platform/signals": { kind: "operator", doing: "reading the platform's signals" },
  "GET /api/v1/platform/nodes": { kind: "operator", doing: "reading the platform's nodes" },
  "GET /api/v1/platform/workloads": { kind: "operator", doing: "reading the platform's workloads" },
  "GET /api/v1/platform/edge": { kind: "operator", doing: "reading the platform's edge" },
  "GET /api/v1/platform/storage": { kind: "operator", doing: "reading the platform's storage" },
  "GET /api/v1/platform/events": { kind: "operator", doing: "reading the platform's cluster events" },
  "GET /api/v1/platform/ingest": { kind: "operator", doing: "reading the platform's ingest" },
  "GET /api/v1/platform/retention": { kind: "operator", doing: "reading the platform's retention" },
  "PATCH /api/v1/platform/retention": { kind: "operator", doing: "changing the platform's retention" },
  "GET /api/v1/platform/backup": { kind: "operator", doing: "reading what a platform backup would carry" },
  "POST /api/v1/platform/backup": { kind: "operator", doing: "exporting the platform's state" },
  "GET /api/v1/settings": { kind: "operator", doing: "reading the platform's settings" },
  "PATCH /api/v1/settings": { kind: "operator", doing: "changing the platform's settings" },
  "GET /api/v1/updates": { kind: "operator", doing: "reading the platform's updates" },
  "POST /api/v1/updates": { kind: "operator", doing: "upgrading the platform" },
  "GET /api/v1/updates/{name}": { kind: "operator", doing: "reading a platform update" },
  "GET /api/v1/updates/{name}/logs": { kind: "operator", doing: "reading a platform update's logs" },
  "GET /api/v1/connections": { kind: "roleShapedBody", doing: "choosing a connection" },
  "GET /api/v1/connections/{name}/repositories": { kind: "authenticated" },
  "POST /api/v1/connections/{name}/detect": { kind: "authenticated" },
  "POST /api/v1/connections": { kind: "operator", doing: "adding a connection" },
  "POST /api/v1/connections/test": { kind: "operator", doing: "testing a connection" },
  "GET /api/v1/connections/{name}": { kind: "operator", doing: "reading a connection" },
  "PATCH /api/v1/connections/{name}": { kind: "operator", doing: "changing a connection" },
  "DELETE /api/v1/connections/{name}": { kind: "operator", doing: "deleting a connection" },
  "GET /api/v1/domains": { kind: "visibleProjects" },
  "POST /api/v1/domains": { kind: "projectRole", role: "developer", doing: "attaching a domain" },
  "GET /api/v1/domains/{name}": { kind: "projectRole", role: "viewer", doing: "reading a domain" },
  "DELETE /api/v1/domains/{name}": { kind: "projectRole", role: "developer", doing: "removing a domain" },
  "GET /api/v1/claims": { kind: "visibleProjects" },
  "POST /api/v1/claims": { kind: "projectRole", role: "developer", doing: "claiming a resource" },
  "GET /api/v1/claims/{name}": { kind: "projectRole", role: "viewer", doing: "reading a resource claim" },
  "DELETE /api/v1/claims/{name}": { kind: "projectRole", role: "developer", doing: "deleting a resource claim" },
  "/": { kind: "authenticated" },
};
