#!/usr/bin/env bash
# Regenerate the parts of the Helm chart that are derived from controller-gen
# output: the CRDs (config/crd/bases) and the manager ClusterRole rules
# (config/rbac/role.yaml).
#
# The chart ships CRDs as regular templates rather than in the crds/ directory,
# so that `helm upgrade` applies schema changes. Generated bodies are copied
# verbatim; only the metadata headers are re-emitted so the chart can attach its
# labels and the optional resource-policy annotation.
#
# Run `make helm-manifests` after `make manifests`. CI fails if the checked-in
# output differs from a fresh run.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
crd_dir="${repo_root}/config/crd/bases"
role_file="${repo_root}/config/rbac/role.yaml"
template_dir="${repo_root}/charts/kitchen/templates"

mkdir -p "${template_dir}"

generated_header() {
  echo '{{/*'
  echo "Generated by hack/gen-helm-manifests.sh from ${1}. DO NOT EDIT."
  echo 'Run `make helm-manifests` after `make manifests` to refresh.'
  echo '*/}}'
}

# --- CRDs -------------------------------------------------------------------
crds_out="${template_dir}/crds.yaml"
{
  generated_header "config/crd/bases"
  echo '{{- if .Values.crds.install }}'

  for file in "${crd_dir}"/*.yaml; do
    name="$(sed -n 's/^  name: \(.*\)$/\1/p' "${file}" | head -1)"
    gen_version="$(sed -n 's|^    controller-gen.kubebuilder.io/version: \(.*\)$|\1|p' "${file}" | head -1)"
    if [[ -z "${name}" ]]; then
      echo "error: could not determine the CRD name in ${file}" >&2
      exit 1
    fi
    if ! grep -q '^spec:' "${file}"; then
      echo "error: no top-level spec in ${file}" >&2
      exit 1
    fi

    echo '---'
    echo 'apiVersion: apiextensions.k8s.io/v1'
    echo 'kind: CustomResourceDefinition'
    echo 'metadata:'
    echo '  annotations:'
    if [[ -n "${gen_version}" ]]; then
      echo "    controller-gen.kubebuilder.io/version: ${gen_version}"
    fi
    echo '    {{- if .Values.crds.keep }}'
    echo '    helm.sh/resource-policy: keep'
    echo '    {{- end }}'
    echo '  labels:'
    echo '    {{- include "kitchen.labels" . | nindent 4 }}'
    echo "  name: ${name}"
    sed -n '/^spec:/,$p' "${file}"
  done

  echo '{{- end }}'
} >"${crds_out}"

# --- Manager ClusterRole ----------------------------------------------------
role_out="${template_dir}/manager-clusterrole.yaml"
if ! grep -q '^rules:' "${role_file}"; then
  echo "error: no top-level rules in ${role_file}" >&2
  exit 1
fi
{
  generated_header "config/rbac/role.yaml"
  echo '{{- if .Values.rbac.create }}'
  echo 'apiVersion: rbac.authorization.k8s.io/v1'
  echo 'kind: ClusterRole'
  echo 'metadata:'
  echo '  name: {{ include "kitchen.fullname" . }}-manager-role'
  echo '  labels:'
  echo '    {{- include "kitchen.labels" . | nindent 4 }}'
  sed -n '/^rules:/,$p' "${role_file}"
  echo '{{- end }}'
} >"${role_out}"

echo "wrote ${crds_out}"
echo "wrote ${role_out}"
