/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Package declarations gathers what every claim provider declares about
// itself (internal/provider/contract) into one table, in the order the
// claim types are registered, so that the reconciler, the API, the docs
// generator and the tests all read the same rows.
//
// Each contract package keeps its own declarations next to its
// implementations — database.Declarations, oidcclient.Declaration — and this
// package only lists them. The matrix in docs/api/claims.md is rendered from
// here by hack/gen-claim-matrix, and the test in this package fails when the
// checked-in matrix and a fresh render differ, which is what keeps prose
// from drifting away from code.
package declarations

import (
	"fmt"
	"strings"

	kitchenv1alpha1 "github.com/Bermos/Kitchen/api/v1alpha1"
	"github.com/Bermos/Kitchen/internal/provider/contract"
	"github.com/Bermos/Kitchen/internal/provider/database"
	"github.com/Bermos/Kitchen/internal/provider/oidcclient"
)

// Declared is one provider's declaration for one claim type.
type Declared struct {
	// Type is the claim type, the value of spec.type.
	Type string
	// Provider is the Connection provider that fulfils it, or the
	// platform's own name for a type it provisions itself.
	Provider string
	contract.Declaration
}

// All is every declaration, claim types in table order and providers in
// the order each contract lists them.
func All() []Declared {
	all := []Declared{}
	for _, claimType := range kitchenv1alpha1.ClaimTypes {
		for _, provider := range providersOf(claimType.Name) {
			declaration, _ := Lookup(claimType.Name, provider)
			all = append(all, Declared{Type: claimType.Name, Provider: provider, Declaration: declaration})
		}
	}
	return all
}

// Lookup is the declaration of one provider for one claim type; ok is false
// for a pair nothing declares, which the reconciler reads as a provider that
// has said nothing about previews and therefore gives them nothing.
func Lookup(claimType, provider string) (contract.Declaration, bool) {
	switch claimType {
	case kitchenv1alpha1.ClaimTypePostgres:
		declaration, ok := database.Declarations[provider]
		return declaration, ok
	case kitchenv1alpha1.ClaimTypeOIDCClient:
		if provider == oidcclient.ProviderName {
			return oidcclient.Declaration, true
		}
	}
	return contract.Declaration{}, false
}

// providersOf is the providers a claim type can be fulfilled by, in a fixed
// order: a generator whose output moves between runs makes the drift check
// fail at random, which teaches everybody to ignore it.
func providersOf(claimType string) []string {
	switch claimType {
	case kitchenv1alpha1.ClaimTypePostgres:
		return []string{database.ProviderNeon, database.ProviderCNPG}
	case kitchenv1alpha1.ClaimTypeOIDCClient:
		return []string{oidcclient.ProviderName}
	}
	return nil
}

// Matrix renders every declaration as the Markdown table docs/api/claims.md
// carries, between its generated markers.
func Matrix() string {
	var b strings.Builder
	b.WriteString("| Type | Provider | Previews get | Scale to zero | Deploys |\n")
	b.WriteString("|---|---|---|---|---|\n")
	for _, d := range All() {
		idling := "unaffected"
		if d.KeepsPodsRunning {
			idling = "**blocked** — " + d.WorkloadNote
		}
		deploys := "unaffected"
		if d.ForcesRecreate {
			deploys = "**recreate, with downtime** — " + d.WorkloadNote
		}
		fmt.Fprintf(&b, "| `%s` | `%s` | `%s` — %s | %s | %s |\n",
			d.Type, d.Provider, d.Preview, d.PreviewNote, idling, deploys)
	}
	return b.String()
}

// Markers delimit the generated block in docs/api/claims.md. The prose
// around it is written by hand; only what is between them is the table.
const (
	BeginMarker = "<!-- generated by hack/gen-claim-matrix from internal/provider/declarations; do not edit -->"
	EndMarker   = "<!-- end generated -->"
)

// Splice replaces the block between the markers in doc with the matrix, and
// fails when the markers are missing: a docs page without them is a page
// the generator cannot keep honest.
func Splice(doc string) (string, error) {
	begin := strings.Index(doc, BeginMarker)
	end := strings.Index(doc, EndMarker)
	if begin < 0 || end < 0 || end < begin {
		return "", fmt.Errorf("the document does not carry the %q … %q markers", BeginMarker, EndMarker)
	}
	return doc[:begin] + BeginMarker + "\n" + Matrix() + EndMarker + doc[end+len(EndMarker):], nil
}
