import { createServer as createTCPServer } from "node:net";
import type { Server } from "node:http";
import { randomBytes } from "node:crypto";

import { authOptions, createAuth, type Auth } from "../src/auth.js";
import type { Config } from "../src/config.js";
import { createPool, runMigrations, waitForDatabase } from "../src/db.js";
import { seedServiceCredential } from "../src/seed.js";
import { createServer } from "../src/server.js";
import type { Pool } from "pg";

/**
 * Integration tests run against a real Postgres, because the schema is
 * generated by better-auth from the plugin set: a fake would only ever prove
 * that the fake agrees with itself.
 */
export const DATABASE_URL =
	process.env.KITCHEN_AUTH_TEST_DATABASE_URL ??
	"postgres://postgres@127.0.0.1:5433/kitchen_auth_test";

export interface Harness {
	url: string;
	config: Config;
	auth: Auth;
	pool: Pool;
	serviceKey: string;
	bootstrapToken: string;
	fetch: (path: string, init?: RequestInit) => Promise<Response>;
	stop: () => Promise<void>;
}

async function freePort(): Promise<number> {
	const probe = createTCPServer();
	await new Promise<void>((resolve) => probe.listen(0, "127.0.0.1", resolve));
	const address = probe.address();
	const port = typeof address === "object" && address ? address.port : 0;
	await new Promise<void>((resolve) => probe.close(() => resolve()));
	return port;
}

/** Drops everything so each run starts from an empty schema. */
async function resetSchema(pool: Pool): Promise<void> {
	await pool.query("DROP SCHEMA public CASCADE");
	await pool.query("CREATE SCHEMA public");
}

export async function startHarness(overrides: Partial<Config> = {}): Promise<Harness> {
	const port = await freePort();
	// 64 characters: the api-key plugin's minimum, and what the chart generates.
	const serviceKey = randomBytes(32).toString("hex");
	const bootstrapToken = randomBytes(16).toString("hex");
	const config: Config = {
		port,
		baseURL: `http://127.0.0.1:${port}`,
		secret: randomBytes(32).toString("hex"),
		databaseURL: DATABASE_URL,
		databaseWaitSeconds: 30,
		serviceKey,
		serviceAccountEmail: "operator@kitchen.local",
		bootstrapToken,
		trustedOrigins: [],
		allowSocialSignUp: false,
		...overrides,
	};

	const pool = createPool(config.databaseURL);
	await waitForDatabase(pool, config.databaseWaitSeconds);
	await resetSchema(pool);
	await runMigrations(authOptions(config, pool), pool);

	const auth = createAuth(config, pool);
	await seedServiceCredential(auth, config);

	const server: Server = createServer(auth, config, pool);
	await new Promise<void>((resolve) => server.listen(port, "127.0.0.1", resolve));

	return {
		url: config.baseURL,
		config,
		auth,
		pool,
		serviceKey: config.serviceKey ?? "",
		bootstrapToken: config.bootstrapToken ?? "",
		fetch: (path, init) => fetch(`${config.baseURL}${path}`, init),
		stop: async () => {
			await new Promise<void>((resolve) => server.close(() => resolve()));
			await pool.end();
		},
	};
}
